name: converter

services:
  backend:
    image: kekishev/converter:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_URL: ${DATABASE_URL}
      EMAIL_ADDRESS: ${EMAIL_ADDRESS}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_SENDER_ADDRESS: ${EMAIL_SENDER_ADDRESS}
    volumes:
      - /root/projects/converter/logs/backend:/logs

  db:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "1234:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
